[package] 
name = "api-test"
version = "0.1.0"
authors = ["Ryan Weiss <rw3iss@gmail.com>"]
edition = "2018"

[dependencies]
may_minihttp = { git = "https://github.com/Xudong-Huang/may_minihttp.git" }
serde = {version = "1.0", features = ["derive"] }
serde_json = "1.0"
may = "0.3.18"